def configure(ctx):
    print("polyorctest configure")
    ctx.standard_defs()
    ctx.write_config_header('config.h')

def build(ctx):
    ctx.program(
        source      = 'main.c testpolyorcbintree.c',
        target      = 'polyorctest',
        includes    = '.',
        libpath     = ['/usr/lib', '/usr/local/lib'],
        cflags      = [ '-Wall', '-g' ],
        use         = 'intern_polyorclib'
    )
