
def configure(ctx):
    print("polyorcboss configure")
    ctx.standard_defs()
    ctx.write_config_header('config.h')

def build(ctx):
    ctx.program(
        source      = 'main.c',
        target      = 'polyorcboss',
        includes    = '.',
        libpath     = ['/usr/lib', '/usr/local/lib'],
        cflags      = [ '-Wall', '-g' ],
        use         = 'intern_polyorclib'
    )
