
def configure(ctx):
    print("polyorclib configure")
    ctx.standard_defs()
    ctx.libckok('uriparser', 'uriparser/Uri.h')
    ctx.write_config_header('config.h')

def build(ctx):
    ctx.stlib(
        target          = 'polyorclib',
        export_includes = '.',
        includes        = '.',
        source          = ['polyorcutils.c',
                           'polyorcmatcher.c',
                           'polyorcbintree.c',
                           'polyorcout.c'],
        cflags          = [ '-Wall', '-g' ],
        name            = "intern_polyorclib"
    )
